### ISSUE TITLE
Auto-teardown for exceptions not working in async driver

### ISSUE THREAD

**Issue by oubiwann** [clojusc/mesomatic#15]
The official Mesos examples come with an "exception" framework that simply shows how a framework behaves when a framework encounters an exception.

When running analogous code in Mesomatic using the standard (synchronous) driver, the same behaviour is seen. However, when using the async driver, the framework hangs.

**Comment by oubiwann** [comment]
Here's the "official" example in action:

```
$ ./src/examples/java/test-exception-framework 10.0.4.193:5050
```

```
I0620 16:59:42.423934  7095 sched.cpp:222] Version: 0.28.2
I0620 16:59:42.430929  7108 sched.cpp:326] New master detected at master@10.0.4.193:5050
I0620 16:59:42.431921  7108 sched.cpp:336] No credentials provided. Attempting to register without authentication
I0620 16:59:42.436880  7108 sched.cpp:703] Framework registered with 3e7bec50-3217-49af-b7fa-55b3e732208a-0006
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException
    at TestExceptionFramework$TestExceptionScheduler.registered(TestExceptionFramework.java:35)
I0620 16:59:42.443181  7108 sched.cpp:1945] Asked to abort the driver
I0620 16:59:42.443653  7108 sched.cpp:1173] Aborting framework '3e7bec50-3217-49af-b7fa-55b3e732208a-0006'
I0620 16:59:42.444752  7095 sched.cpp:1911] Asked to stop the driver
I0620 16:59:42.444862  7115 sched.cpp:1143] Stopping framework '3e7bec50-3217-49af-b7fa-55b3e732208a-0006'
```

Here's a similar "exception" framework written with Mesomatic:

```
$ lein mesomatic 10.0.4.193:5050 exception-framework || echo $?
```

``` clj
2016-06-20 16:59:56,884 [main] INFO  clojusc.mesomatic.example.core - Running mesomatic-example! 
2016-06-20 16:59:56,886 [main] DEBUG clojusc.mesomatic.example.core - Using master: 10.0.4.193:5050 
2016-06-20 16:59:56,886 [main] DEBUG clojusc.mesomatic.example.core - Got task-type: exception-framework 
2016-06-20 16:59:56,886 [main] INFO  c.m.e.exception-framework - Running example exception-framework ... 
2016-06-20 16:59:56,950 [main] DEBUG c.m.e.exception-framework - Starting example scheduler ... 
I0620 16:59:56.952066  7162 sched.cpp:222] Version: 0.28.2
2016-06-20 16:59:56,952 [main] DEBUG c.m.e.exception-framework - Reducing over example scheduler channel messages ... 
I0620 16:59:56.959060  7184 sched.cpp:326] New master detected at master@10.0.4.193:5050
I0620 16:59:56.959846  7184 sched.cpp:336] No credentials provided. Attempting to register without authentication
I0620 16:59:56.963027  7181 sched.cpp:703] Framework registered with 3e7bec50-3217-49af-b7fa-55b3e732208a-0007
2016-06-20 16:59:56,967 [async-dispatch-2] WARN  c.m.e.exception-framework - Preparing to throw exception: 
Exception in thread "async-dispatch-2" java.lang.Error: java.lang.Exception: Throwing an exception ...
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1151)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Throwing an exception ...
    at clojusc.mesomatic.example.exception_framework$eval12304$fn__12305.invoke(exception_framework.clj:61)
    at clojure.lang.MultiFn.invoke(MultiFn.java:233)
    at clojure.core.async$reduce$fn__6074$state_machine__5528__auto____6075$fn__6077.invoke(async.clj:596)
    at clojure.core.async$reduce$fn__6074$state_machine__5528__auto____6075.invoke(async.clj:596)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:1011)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1010)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:1015)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1013)
    at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5544.invoke(ioc_macros.clj:1024)
    at clojure.core.async.impl.channels.ManyToManyChannel$fn__466.invoke(channels.clj:135)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    ... 2 more
```

**Comment by oubiwann** [comment]
I haven't dug into this at all ... but I was wondering if we could add a `try`/`catch` wrap that sends a message back to the framework such that the synchronous behaviour could be duplicated (via a response to the sent message). Dunno.

**Comment by pyr** [comment]
Thanks for this @oubiwann, will look into it

**Comment by pyr** [comment]
So indeed the scheduler drivers catches uncaught exceptions and use them as an indication that the framework should be stopped. 

In the case of async frameworks, execution of the callback code happens on 
a different code path since all the scheduler callbacks do is enqueue messages onto a channel.

Exceptions will have to be caught on the receiving end of the channel.
If you're using `a/reduce` it could look like:

``` clojure
(defmulti handle-msg (comp :type last vector))

(defn wrap-handler                                                                                                
  [state payload]                                                                                                
  (try                                                                                                           
    (handle-msg state payload)                                                                                   
    (catch Exception e                                                                                           
      (let [driver (:driver state)]                                                                              
        (scheduler/abort! driver)                                                                                
        (reduced                                                                                                 
         (assoc state :error e))))))

(defn -main
   [& args]
   ...
   (scheduler/start! driver)
   (a/reduce wrap-handler  {:driver driver} ch)
   (scheduler/join! driver))
```

A generic wrapper is used to catch exceptions and when one is caught, two things happen:
- `abort!` is called on the driver
- by wrapping the result in `reduced`, `a/reduce` will stop waiting for new values on the channel, the
  rest of the standard tear-down can happen.

**Comment by oubiwann** [comment]
This is fantastic -- thanks! Just what I needed :-)

Your solution is quite nice; I'll go ahead and close the ticket ...
