### ISSUE TITLE
NoSuchMethodError for org.apache.mesos.Protos$Value$Set.getItemList

### ISSUE THREAD

**Issue by oubiwann** [clojusc/mesomatic#33]
This is a new one for me ... I'm not sure what has changed, but I wasn't getting this error last week :-/

(I _might_ have still had an older jar file in my path, which would explain the sudden occurrence.)

When I kick off a new framework and the first resource offer is being processed, I get this error:

```
Exception in thread "Thread-7" java.lang.NoSuchMethodError: org.apache.mesos.Protos$Value$Set.getItemList()Lcom/google/protobuf/ProtocolStringList;
    at mesomatic.types$fn__819.invokeStatic(types.clj:596)
    at mesomatic.types$fn__819.invoke(types.clj:594)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at mesomatic.types$fn__929.invokeStatic(types.clj:675)
    at mesomatic.types$fn__929.invoke(types.clj:667)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
    at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6545)
    at clojure.core$mapv.invokeStatic(core.clj:6618)
    at clojure.core$mapv.invoke(core.clj:6618)
    at mesomatic.types$fn__1298.invokeStatic(types.clj:1031)
    at mesomatic.types$fn__1298.invoke(types.clj:1024)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
    at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6545)
    at clojure.core$mapv.invokeStatic(core.clj:6618)
    at clojure.core$mapv.invoke(core.clj:6618)
    at mesomatic.scheduler$wrap_scheduler$reify__2859.resourceOffers(scheduler.clj:113)
```

Looking at `mesomatic.types`, this is the code that seems to be bombing out:

```
(defmethod pb->data Protos$Value$Set
  [^Protos$Value$Set value-set]
 (set (.getItemList value-set)))
```

And, indeed, when I look at the Protobuf docs, I don't see this method defined for `ProtocolStringList`:
- https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/ProtocolStringList

I'm not sure if `Protos$Value$Set` is supposed to be a `ProtocolStringList` or not ...

**Comment by oubiwann** [comment]
I've actually been running mesomatic 1.0.1-r0 against 1.0.0, so I'm going to download and build a new 1.0.1 before I continue debugging (just in case).

**Comment by oubiwann** [comment]
A new build of 1.0.1 gives me the same error. Will dig into this more tomorrow ...

**Comment by oubiwann** [comment]
Last night while falling asleep, I had the thought that this bug might actually be due to an inadvertent change by a calling function ... one that might now be passing an invalid data type. 

If that turns out to be the case, I'll just close this as "invalid" ;-)

**Comment by oubiwann** [comment]
Found an issue (#34, potentially related?) and will test this issue against that fix when it's in place.

**Comment by oubiwann** [comment]
Another issue which may affect this one: #35.

**Comment by oubiwann** [comment]
Sweet -- with fixes in place for the two issues found above, the error for this ticket goes away.

Closing as a symptom, not an actual issue.
